name: Build

on: [push]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]
        # python: [3.7, 3.8, 3.9, 3.10]
        python: [3.7]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      # Used to host cibuildwheel
      - uses: actions/setup-python@v5

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.19.0

      # Install Linux dependencies
      - name: Update deb repository
        if: runner.os == 'Linux'
        run: sudo apt-get update

      - name: Install deb dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get install -y xorg-dev libglu1-mesa-dev libglew-dev xvfb

      # Build wheels
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value

      # Upload wheels
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl